# Helper methods defined here can be accessed in any controller or view in the application

Multiselect.helpers do
  def countries optgroup = false
    array = [
      ['test', ''],
      ['France', "fr"],
      ['United Kingdom', "uk"],
      ['United States', "us"],
      ['China', "ch"],
      ['Australia', "au"],
      ['India', "in"],
      ['Argentina', "ar"],
      ['Brazil', "br"],
      ['Tibet', "tb"],
      ['Columbia', "co"],
      ['Croatia', "cr"],
      ['Italia', "it"],
      ['Espana', "es"],
      ['Indonesia', "id"],
      ['Germany', "du"],
      ['Norway', "no"]
      #,
      # ['France', "fr1"],
      # ['United Kingdom', "uk1"],
      # ['United States', "us1"],
      # ['China', "ch1"],
      # ['Australia', "au1"],
      # ['India', "in1"],
      # ['Argentina', "ar1"],
      # ['Brazil', "br1"],
      # ['Tibet', "tb1"],
      # ['Columbia', "co1"],
      # ['Croatia', "cr1"],
      # ['Italia', "it1"],
      # ['Espana', "es1"],
      # ['Indonesia', "id1"],
      # ['Germany', "du1"],
      # ['Norway', "no1"],
      # ['France', "fr2"],
      # ['United Kingdom', "uk2"],
      # ['United States', "us2"],
      # ['China', "ch2"],
      # ['Australia', "au2"],
      # ['India', "in2"],
      # ['Argentina', "ar2"],
      # ['Brazil', "br2"],
      # ['Tibet', "tb2"],
      # ['Columbia', "co2"],
      # ['Croatia', "cr2"],
      # ['Italia', "it2"],
      # ['Espana', "es2"],
      # ['Indonesia', "id2"],
      # ['Germany', "du2"],
      # ['Norway', "no2"],
      # ['France', "fr3"],
      # ['United Kingdom', "uk3"],
      # ['United States', "us3"],
      # ['China', "ch3"],
      # ['Australia', "au3"],
      # ['India', "in3"],
      # ['Argentina', "ar3"],
      # ['Brazil', "br3"],
      # ['Tibet', "tb3"],
      # ['Columbia', "co3"],
      # ['Croatia', "cr3"],
      # ['Italia', "it3"],
      # ['Espana', "es3"],
      # ['Indonesia', "id3"],
      # ['Germany', "du3"],
      # ['Norway', "no3"],
      # ['France', "fr4"],
      # ['United Kingdom', "uk4"],
      # ['United States', "us4"],
      # ['China', "ch4"],
      # ['Australia', "au4"],
      # ['India', "in4"],
      # ['Argentina', "ar4"],
      # ['Brazil', "br4"],
      # ['Tibet', "tb4"],
      # ['Columbia', "co4"],
      # ['Croatia', "cr4"],
      # ['Italia', "it4"],
      # ['Espana', "es4"],
      # ['Indonesia', "id4"],
      # ['Germany', "du4"],
      # ['Norway', "no4"],
      # ['France', "fr5"],
      # ['United Kingdom', "uk5"],
      # ['United States', "us5"],
      # ['China', "ch5"],
      # ['Australia', "au5"],
      # ['India', "in5"],
      # ['Argentina', "ar5"],
      # ['Brazil', "br5"],
      # ['Tibet', "tb5"],
      # ['Columbia', "co5"],
      # ['Croatia', "cr5"],
      # ['Italia', "it5"],
      # ['Espana', "es5"],
      # ['Indonesia', "id5"],
      # ['Germany', "du5"],
      # ['Norway', "no5"],
      # ['France', "fr6"],
      # ['United Kingdom', "uk6"],
      # ['United States', "us6"],
      # ['China', "ch6"],
      # ['Australia', "au6"],
      # ['India', "in6"],
      # ['Argentina', "ar6"],
      # ['Brazil', "br6"],
      # ['Tibet', "tb6"],
      # ['Columbia', "co6"],
      # ['Croatia', "cr6"],
      # ['Italia', "it6"],
      # ['Espana', "es6"],
      # ['Indonesia', "id6"],
      # ['Germany', "du6"],
      # ['Norway', "no6"],
      # ['France', "fr11"],
      # ['United Kingdom', "uk11"],
      # ['United States', "us11"],
      # ['China', "ch11"],
      # ['Australia', "au11"],
      # ['India', "in11"],
      # ['Argentina', "ar11"],
      # ['Brazil', "br11"],
      # ['Tibet', "tb11"],
      # ['Columbia', "co11"],
      # ['Croatia', "cr11"],
      # ['Italia', "it11"],
      # ['Espana', "es11"],
      # ['Indonesia', "id11"],
      # ['Germany', "du11"],
      # ['Norway', "no11"],
      # ['France', "fr21"],
      # ['United Kingdom', "uk21"],
      # ['United States', "us21"],
      # ['China', "ch21"],
      # ['Australia', "au21"],
      # ['India', "in21"],
      # ['Argentina', "ar21"],
      # ['Brazil', "br21"],
      # ['Tibet', "tb21"],
      # ['Columbia', "co21"],
      # ['Croatia', "cr21"],
      # ['Italia', "it21"],
      # ['Espana', "es21"],
      # ['Indonesia', "id21"],
      # ['Germany', "du21"],
      # ['Norway', "no21"],
      # ['France', "fr31"],
      # ['United Kingdom', "uk31"],
      # ['United States', "us31"],
      # ['China', "ch31"],
      # ['Australia', "au31"],
      # ['India', "in31"],
      # ['Argentina', "ar31"],
      # ['Brazil', "br31"],
      # ['Tibet', "tb31"],
      # ['Columbia', "co31"],
      # ['Croatia', "cr31"],
      # ['Italia', "it31"],
      # ['Espana', "es31"],
      # ['Indonesia', "id31"],
      # ['Germany', "du31"],
      # ['Norway', "no31"],
      # ['France', "fr41"],
      # ['United Kingdom', "uk41"],
      # ['United States', "us41"],
      # ['China', "ch41"],
      # ['Australia', "au41"],
      # ['India', "in41"],
      # ['Argentina', "ar41"],
      # ['Brazil', "br41"],
      # ['Tibet', "tb41"],
      # ['Columbia', "co41"],
      # ['Croatia', "cr41"],
      # ['Italia', "it41"],
      # ['Espana', "es41"],
      # ['Indonesia', "id41"],
      # ['Germany', "du41"],
      # ['Norway', "no41"],
      # ['France', "fr51"],
      # ['United Kingdom', "uk51"],
      # ['United States', "us51"],
      # ['China', "ch51"],
      # ['Australia', "au51"],
      # ['India', "in51"],
      # ['Argentina', "ar51"],
      # ['Brazil', "br51"],
      # ['Tibet', "tb51"],
      # ['Columbia', "co51"],
      # ['Croatia', "cr51"],
      # ['Italia', "it51"],
      # ['Espana', "es51"],
      # ['Indonesia', "id51"],
      # ['Germany', "du51"],
      # ['Norway', "no51"],
      # ['France', "fr61"],
      # ['United Kingdom', "uk61"],
      # ['United States', "us61"],
      # ['China', "ch61"],
      # ['Australia', "au61"],
      # ['India', "in61"],
      # ['Argentina', "ar61"],
      # ['Brazil', "br61"],
      # ['Tibet', "tb61"],
      # ['Columbia', "co61"],
      # ['Croatia', "cr61"],
      # ['Italia', "it61"],
      # ['Espana', "es61"],
      # ['Indonesia', "id61"],
      # ['Germany', "du61"],
      # ['Norway', "no61"],
      # ['France', "fr12"],
      # ['United Kingdom', "uk12"],
      # ['United States', "us12"],
      # ['China', "ch12"],
      # ['Australia', "au12"],
      # ['India', "in12"],
      # ['Argentina', "ar12"],
      # ['Brazil', "br12"],
      # ['Tibet', "tb12"],
      # ['Columbia', "co12"],
      # ['Croatia', "cr12"],
      # ['Italia', "it12"],
      # ['Espana', "es12"],
      # ['Indonesia', "id12"],
      # ['Germany', "du12"],
      # ['Norway', "no12"],
      # ['France', "fr22"],
      # ['United Kingdom', "uk22"],
      # ['United States', "us22"],
      # ['China', "ch22"],
      # ['Australia', "au22"],
      # ['India', "in22"],
      # ['Argentina', "ar22"],
      # ['Brazil', "br22"],
      # ['Tibet', "tb22"],
      # ['Columbia', "co22"],
      # ['Croatia', "cr22"],
      # ['Italia', "it22"],
      # ['Espana', "es22"],
      # ['Indonesia', "id22"],
      # ['Germany', "du22"],
      # ['Norway', "no22"],
      # ['France', "fr32"],
      # ['United Kingdom', "uk32"],
      # ['United States', "us32"],
      # ['China', "ch32"],
      # ['Australia', "au32"],
      # ['India', "in32"],
      # ['Argentina', "ar32"],
      # ['Brazil', "br32"],
      # ['Tibet', "tb32"],
      # ['Columbia', "co32"],
      # ['Croatia', "cr32"],
      # ['Italia', "it32"],
      # ['Espana', "es32"],
      # ['Indonesia', "id32"],
      # ['Germany', "du32"],
      # ['Norway', "no32"],
      # ['France', "fr42"],
      # ['United Kingdom', "uk42"],
      # ['United States', "us42"],
      # ['China', "ch42"],
      # ['Australia', "au42"],
      # ['India', "in42"],
      # ['Argentina', "ar42"],
      # ['Brazil', "br42"],
      # ['Tibet', "tb42"],
      # ['Columbia', "co42"],
      # ['Croatia', "cr42"],
      # ['Italia', "it42"],
      # ['Espana', "es42"],
      # ['Indonesia', "id42"],
      # ['Germany', "du42"],
      # ['Norway', "no42"],
      # ['France', "fr52"],
      # ['United Kingdom', "uk52"],
      # ['United States', "us52"],
      # ['China', "ch52"],
      # ['Australia', "au52"],
      # ['India', "in52"],
      # ['Argentina', "ar52"],
      # ['Brazil', "br52"],
      # ['Tibet', "tb52"],
      # ['Columbia', "co52"],
      # ['Croatia', "cr52"],
      # ['Italia', "it52"],
      # ['Espana', "es52"],
      # ['Indonesia', "id52"],
      # ['Germany', "du52"],
      # ['Norway', "no52"],
      # ['France', "fr62"],
      # ['United Kingdom', "uk62"],
      # ['United States', "us62"],
      # ['China', "ch62"],
      # ['Australia', "au62"],
      # ['India', "in62"],
      # ['Argentina', "ar62"],
      # ['Brazil', "br62"],
      # ['Tibet', "tb62"],
      # ['Columbia', "co62"],
      # ['Croatia', "cr62"],
      # ['Italia', "it62"],
      # ['Espana', "es62"],
      # ['Indonesia', "id62"],
      # ['Germany', "du62"],
      # ['Norway', "no61"]
    ]
    array.map{ |a| ['europe', a]} if optgroup
    array
  end
end
